# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce5b60cdd46ce23d11152c18630fb25ea61cc7e766e7c0c5d60d25de7f7b62a5b27c5abf1979edff90fdaa526df225947336127d19810f378609eacc4fd1c04c

test:
  secret_key_base: 8ca3445134b79b6628a21dfa3dcbd1b04631c7aaeb4044749786c7e133e548318e7087e56252b6e6eb89142b028d27cefd770e4164e797b34335de4ed1b4b064

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
